diffusion:
  beta_end: 0.5
  beta_start: 0.0001
  channels: 64
  diffusion_embedding_dim: 128
  layers: 4
  num_steps: 100
  tau_steps: 50
  schedule: quad
  method: mlp
  mlp_hidden_dim: 128
model:
  featureemb: 16
  covariateemb: 8
  timeemb: 128
train:
  batch_size: 8
  epochs: 50
  lr: 0.001
  eta: 1