diffusion:
  beta_end: 0.5
  beta_start: 0.0001
  channels: 64
  diffusion_embedding_dim: 128
  layers: 4
  num_steps: 50
  schedule: quad
  method: mlp
  transformer:
    name: linear
    nheads: 8
    channels: 64
    landmarks: 32
    linformer_k: 128

model:
  featureemb: 16
  dowemb : 8
  houremb: 8
  timeemb: 128
train:
  batch_size: 8
  epochs: 50
  lr: 0.001