diffusion:
  beta_end: 0.5
  beta_start: 0.0001
  channels: 64
  diffusion_embedding_dim: 128
  layers: 8
  nheads: 8
  num_steps: 50
  schedule: quad
model:
  featureemb: 16
  is_unconditional: 0
  timeemb: 128
train:
  batch_size: 4
  epochs: 50
  lr: 0.001
